# Generated by Django 5.2.4 on 2025-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_user_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('illustrations', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('genre', models.CharField(blank=True, max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=150)),
                ('cast', models.CharField(blank=True, max_length=150, null=True)),
                ('synopsis', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'story',
            },
        ),
    ]
