- name: Check if SSH tunnel is already established
  shell: |
    lsof -iTCP:5432 -sTCP:LISTEN
  register: ssh_tunnel_check
  changed_when: false
  failed_when: false
- name: Open SSH tunnel to PostgreSQL 
  shell: |
    ssh -f -N -L 5432:{{ db_hostname }}:5432 {{ app_username }}@{{ app_hostname }} -o ExitOnForwardFailure=yes 
  register: ssh_tunnel_connection 
  failed_when: ssh_tunnel_connection.rc != 0 
  when: ssh_tunnel_check.stdout == "" 
- name: Test PostgreSQL connection via SSH tunnel
  community.postgresql.postgresql_ping: 
    login_db: "postgres"
    login_host: "127.0.0.1"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    port: 5432
    ssl_mode: require
  register: postgresql_ping_result
  failed_when: postgresql_ping_result.failed 
  until: not postgresql_ping_result.failed
  retries: 5
  delay: 2