- name: Create user for identity service
  community.postgresql.postgresql_user:
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    name: "{{ db_identity_username }}"
    password: "{{ db_identity_password }}"
    ssl_mode: require
    state: present 
- name: Create user for users service
  community.postgresql.postgresql_user:
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    name: "{{ db_users_username }}"
    password: "{{ db_users_password }}"
    ssl_mode: require
    state: present