- name: Grant privileges to users service user on database
  community.postgresql.postgresql_privs:
    login_db: "{{ db_users_db }}"
    login_host: "127.0.0.1"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    port: 5432 
    type: database
    privs: CONNECT
    roles: "{{ db_users_username }}"
- name: Grant privileges to users service user on schema public
  community.postgresql.postgresql_privs:
    login_db: "{{ db_users_db }}"
    login_host: "127.0.0.1"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    port: 5432 
    schema: public
    type: table
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER
    roles: "{{ db_users_username }}" 
- name: Grant privileges to users service user on sequences
  community.postgresql.postgresql_privs:  
    login_db: "{{ db_users_db }}"
    login_host: "127.0.0.1"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    port: 5432 
    schema: public
    type: sequence
    objs: ALL_IN_SCHEMA
    privs: USAGE,SELECT,UPDATE
    roles: "{{ db_users_username }}"
- name: Grant privileges to users service user on functions
  community.postgresql.postgresql_privs:
    login_db: "{{ db_users_db }}"
    login_host: "127.0.0.1"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    port: 5432 
    schema: public
    type: function
    objs: ALL_IN_SCHEMA
    privs: EXECUTE
    roles: "{{ db_users_username }}"
- name: Grant USAGE privilege on schema public to users service user
  community.postgresql.postgresql_privs:
    login_db: "{{ db_users_db }}"
    login_host: "127.0.0.1"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    port: 5432 
    type: schema
    objs: public
    privs: USAGE
    roles: "{{ db_users_username }}"