- import_tasks: ../../common_tasks/tasks/install-ssh_client.yaml
- import_tasks: connection_to_database.yaml
- import_tasks: create_users.yaml
- import_tasks: create_databases.yaml
- import_tasks: grant_privileges_for_users_service_user.yaml
- import_tasks: grant_privileges_for_identity_service_user.yaml
- import_tasks: close_connection_to_database.yaml 