- name: Enable KV secrets engine for django
  ansible.builtin.command: >
    docker exec vault vault secrets enable -path=django kv-v2
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: secrets_engine 
  failed_when: secrets_engine.rc != 0 and 'path is already in use' not in secrets_engine.stderr
  changed_when: secrets_engine.rc == 0

- name: Enable database secrets engine
  ansible.builtin.command: >
    docker exec vault vault secrets enable database
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: database_secrets_engine
  failed_when: database_secrets_engine.rc != 0 and 'path is already in use' not in database_secrets_engine.stderr
  changed_when: database_secrets_engine.rc == 0 

- name: Enable KV secrets engine for redis
  ansible.builtin.command: >
    docker exec vault vault secrets enable -path=redis kv-v2
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: redis_secrets_engine
  failed_when: redis_secrets_engine.rc != 0 and 'path is already in use' not in redis_secrets_engine.stderr 
  changed_when: redis_secrets_engine.rc == 0 
- name: Enable AWS secrets engine for IAM
  ansible.builtin.command: >
    docker exec vault vault secrets enable -path=aws/iam aws
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: aws_iam_secrets_engine
  failed_when: aws_iam_secrets_engine.rc != 0 and 'path is already in use' not in aws_iam_secrets_engine.stderr 
  changed_when: aws_iam_secrets_engine.rc == 0 
- name: Enable KV secrets engine for SES-SMTP
  ansible.builtin.command: >
    docker exec vault vault secrets enable -path=aws/ses/smtp kv-v2
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: ses_smtp_secrets_engine
  failed_when: ses_smtp_secrets_engine.rc != 0 and 'path is already in use' not in ses_smtp_secrets_engine.stderr 
  changed_when: ses_smtp_secrets_engine.rc == 0
- name: Enable TRANSIT secrets engine
  ansible.builtin.command: >
    docker exec vault vault secrets enable transit 
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: transit_secrets_engine
  failed_when: transit_secrets_engine.rc != 0 and 'path is already in use' not in transit_secrets_engine.stderr 
  changed_when: transit_secrets_engine.rc == 0

- name: Enable userpass secrets engine
  ansible.builtin.command: >
    docker exec vault vault auth enable userpass
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: userpass_secrets_engine
  failed_when: userpass_secrets_engine.rc != 0 and 'path is already in use' not in userpass_secrets_engine.stderr 
  changed_when: userpass_secrets_engine.rc == 0
- name: Enable APPROLE secrets engine
  ansible.builtin.command: >
    docker exec vault vault auth enable approle
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: approle_secrets_engine
  failed_when: approle_secrets_engine.rc != 0 and 'path is already in use' not in approle_secrets_engine.stderr 
  changed_when: approle_secrets_engine.rc == 0 

- name: Enable PKI secrets engine
  ansible.builtin.command: >
    docker exec vault vault secrets enable pki
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: pki_secrets_engine
  failed_when: pki_secrets_engine.rc != 0 and 'path is already in use' not in pki_secrets_engine.stderr 
  changed_when: pki_secrets_engine.rc == 0

- name: Enable PKI secrets engine intermediate CA
  ansible.builtin.command: >
    docker exec vault vault secrets enable -path=pki_int pki
  when: vault_connection.skipped is defined or (vault_connection.rc | default(1)) == 0
  register: pki_secrets_engine_pki_int
  failed_when: pki_secrets_engine_pki_int.rc != 0 and 'path is already in use' not in pki_secrets_engine_pki_int.stderr 
  changed_when: pki_secrets_engine_pki_int.rc == 0